name: trash2cash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.1.1
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  uuid: ^4.5.1
  concentric_transition: 1.0.3
  google_fonts: ^6.1.0
  rive: ^0.13.0

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  animate_do: ^4.2.0
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.7

  google_maps_flutter: ^2.5.3

  # OpenStreetMap (GRATIS!)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Location
  geolocator: ^11.0.0
  geocoding: ^2.1.1   

  connectivity_plus: ^5.0.2 

  http: ^1.2.0
  url_launcher: ^6.2.4
  cloudinary_public: ^0.21.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/models/model_unquant.tflite
    - assets/models/labels.txt

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
